import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'tr',
        'en',
        'es',
        'ja',
        'ru',
        'zh_Hans',
        'it',
        'ar',
        'fr',
        'de',
        'el',
        'hi'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? trText = '',
    String? enText = '',
    String? esText = '',
    String? jaText = '',
    String? ruText = '',
    String? zh_HansText = '',
    String? itText = '',
    String? arText = '',
    String? frText = '',
    String? deText = '',
    String? elText = '',
    String? hiText = '',
  }) =>
      [
        trText,
        enText,
        esText,
        jaText,
        ruText,
        zh_HansText,
        itText,
        arText,
        frText,
        deText,
        elText,
        hiText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'zhkx43tz': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // girisyap
  {
    'db95jjfz': {
      'tr': 'Hoşgeldiniz',
      'ar': 'مرحبًا بعودتك',
      'de': 'Willkommen zurück',
      'el': 'Καλώς ήρθατε πίσω',
      'en': 'Welcome Back',
      'es': 'Bienvenido de nuevo',
      'fr': 'Content de te revoir',
      'hi': 'वापसी पर स्वागत है',
      'it': 'Bentornato',
      'ja': 'おかえり',
      'ru': 'Добро пожаловать',
      'zh_Hans': '欢迎回来',
    },
    'vwj3yrcb': {
      'tr': 'Aşağıdaki Formdan Giriş Yapabilirsiniz.',
      'ar': 'لنبدأ بملء النموذج أدناه.',
      'de': 'Beginnen wir, indem Sie das untenstehende Formular ausfüllen.',
      'el': 'Ας ξεκινήσουμε συμπληρώνοντας την παρακάτω φόρμα.',
      'en': 'Let\'s get started by filling out the form below.',
      'es': 'Comencemos rellenando el formulario que aparece a continuación.',
      'fr': 'Commençons par remplir le formulaire ci-dessous.',
      'hi': 'आइये नीचे दिए गए फॉर्म को भरकर शुरुआत करें।',
      'it': 'Iniziamo compilando il modulo sottostante.',
      'ja': 'まずは以下のフォームにご記入ください。',
      'ru': 'Давайте начнем с заполнения формы ниже.',
      'zh_Hans': '让我们开始填写下面的表格。',
    },
    'qrdft29u': {
      'tr': 'Email',
      'ar': 'بريد إلكتروني',
      'de': 'E-Mail',
      'el': 'E-mail',
      'en': 'E-mail',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'it': 'E-mail',
      'ja': 'Eメール',
      'ru': 'Электронная почта',
      'zh_Hans': '电子邮件',
    },
    'uyeuysd9': {
      'tr': 'Password',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'el': 'Σύνθημα',
      'en': 'Password',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'it': 'Password',
      'ja': 'パスワード',
      'ru': 'Пароль',
      'zh_Hans': '密码',
    },
    'xjj920zl': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'uas0kcbv': {
      'tr': 'Şifreni mi Unuttun ?',
      'ar': 'نسيت كلمة السر؟',
      'de': 'Passwort vergessen?',
      'el': 'Ξεχάσατε τον κωδικό πρόσβασής σας;',
      'en': 'Forgot your password?',
      'es': '¿Olvidaste tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'hi': 'अपना कूट शब्द भूल गए?',
      'it': 'Hai dimenticato la password?',
      'ja': 'パスワードをお忘れですか？',
      'ru': 'Забыли пароль?',
      'zh_Hans': '忘记密码了吗？',
    },
    'w8dooeke': {
      'tr': 'Sign In',
      'ar': 'تسجيل الدخول',
      'de': 'Anmelden',
      'el': 'Σύνδεση',
      'en': 'Sign In',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'hi': 'दाखिल करना',
      'it': 'Registrazione',
      'ja': 'サインイン',
      'ru': 'Войти',
      'zh_Hans': '登入',
    },
    'c8xvzkq3': {
      'tr': 'Hesabın yok mu? ',
      'ar': 'ليس لديك حساب؟',
      'de': 'Sie haben noch kein Konto?',
      'el': 'Δεν έχετε λογαριασμό;',
      'en': 'Don\'t have an account?',
      'es': '¿No tienes una cuenta?',
      'fr': 'Vous n\'avez pas de compte ?',
      'hi': 'क्या आपके पास खाता नहीं है?',
      'it': 'Non hai un account?',
      'ja': 'アカウントをお持ちではありませんか？',
      'ru': 'У вас нет учетной записи?',
      'zh_Hans': '沒有帳戶？',
    },
    'a2zm1v92': {
      'tr': 'Sign Up here',
      'ar': 'سجل هنا',
      'de': 'Hier anmelden',
      'el': 'Εγγραφείτε εδώ',
      'en': 'Sign Up here',
      'es': 'Regístrate aquí',
      'fr': 'Inscrivez-vous ici',
      'hi': 'यहां साइन अप करें',
      'it': 'Iscriviti qui',
      'ja': 'こちらにサインアップ',
      'ru': 'Зарегистрируйтесь здесь',
      'zh_Hans': '在此注册',
    },
    '9c77q8mx': {
      'tr': 'UserName',
      'ar': 'اسم المستخدم',
      'de': 'Benutzername',
      'el': 'Ονομα χρήστη',
      'en': 'User Name',
      'es': 'Nombre de usuario',
      'fr': 'Nom d\'utilisateur',
      'hi': 'उपयोगकर्ता नाम',
      'it': 'Nome utente',
      'ja': 'ユーザー名',
      'ru': 'Имя пользователя',
      'zh_Hans': '用户名',
    },
    'duyzv5c5': {
      'tr': 'Overall',
      'ar': 'إجمالي',
      'de': 'Gesamt',
      'el': 'Ολικός',
      'en': 'Overall',
      'es': 'En general',
      'fr': 'Dans l\'ensemble',
      'hi': 'कुल मिलाकर',
      'it': 'Complessivamente',
      'ja': '全体',
      'ru': 'Общий',
      'zh_Hans': '全面的',
    },
    'pftfd4qo': {
      'tr': '5',
      'ar': '5',
      'de': '5',
      'el': '5',
      'en': '5',
      'es': '5',
      'fr': '5',
      'hi': '5',
      'it': '5',
      'ja': '5',
      'ru': '5',
      'zh_Hans': '5',
    },
    '7cfpcnk2': {
      'tr':
          'Nice outdoor courts, solid concrete and good hoops for the neighborhood.',
      'ar': 'ملاعب خارجية جميلة، وخرسانة صلبة وأطواق جيدة للجيران.',
      'de':
          'Schöne Außenplätze, solider Beton und gute Körbe für die Nachbarschaft.',
      'el':
          'Ωραία εξωτερικά γήπεδα, συμπαγές σκυρόδεμα και καλά στεφάνια για τη γειτονιά.',
      'en':
          'Nice outdoor courts, solid concrete and good hoops for the neighborhood.',
      'es':
          'Bonitas canchas al aire libre, concreto solido y buenos aros para el barrio.',
      'fr':
          'De beaux terrains extérieurs, du béton solide et de bons paniers pour le quartier.',
      'hi': 'अच्छे आउटडोर कोर्ट, ठोस कंक्रीट और पड़ोस के लिए अच्छे हुप्स।',
      'it':
          'Bei campi all\'aperto, cemento solido e buoni canestri per il quartiere.',
      'ja': '素晴らしい屋外コート、頑丈なコンクリート、近所に最適なバスケットボールコート。',
      'ru':
          'Хорошие открытые корты, прочный бетон и хорошие баскетбольные корзины для всего района.',
      'zh_Hans': '漂亮的室外球场、坚固的混凝土和适合社区的优质篮球架。',
    },
    'm0ztb20p': {
      'tr': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'el': 'Σπίτι',
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'it': 'Casa',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // hesapolustur
  {
    '5cwhcm4n': {
      'tr': 'Hesap Oluştur',
      'ar': 'إنشاء حساب',
      'de': 'Benutzerkonto erstellen',
      'el': 'Δημιουργία λογαριασμού',
      'en': 'Create Account',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'ru': 'Зарегистрироваться',
      'zh_Hans': '创建账户',
    },
    'tqmxlqay': {
      'tr': 'Başlamak için lütfen aşağıdaki formu doldurun.',
      'ar': 'يرجى ملء النموذج أدناه للبدء.',
      'de': 'Bitte füllen Sie das untenstehende Formular aus, um zu beginnen.',
      'el': 'Παρακαλούμε συμπληρώστε την παρακάτω φόρμα για να ξεκινήσετε.',
      'en': 'Please fill out the form below to get started.',
      'es': 'Por favor, rellene el formulario a continuación para comenzar.',
      'fr': 'Veuillez remplir le formulaire ci-dessous pour commencer.',
      'hi': 'कृपया नीचे दिए फॉर्म को भरने के लिए शुरू करने के लिए।',
      'it': 'Per iniziare, compila il modulo sottostante.',
      'ja': '開始するには、以下のフォームにご記入ください。',
      'ru': 'Чтобы начать, пожалуйста, заполните форму ниже.',
      'zh_Hans': '请填写下面的表格即可开始。',
    },
    'b0vpx8bb': {
      'tr': 'Name',
      'ar': 'اسم',
      'de': 'Name',
      'el': 'Ονομα',
      'en': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'hi': 'नाम',
      'it': 'Nome',
      'ja': '名前',
      'ru': 'Имя',
      'zh_Hans': '姓名',
    },
    'jgfiqg70': {
      'tr': 'Email',
      'ar': 'بريد إلكتروني',
      'de': 'E-Mail',
      'el': 'E-mail',
      'en': 'E-mail',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'it': 'E-mail',
      'ja': 'Eメール',
      'ru': 'Электронная почта',
      'zh_Hans': '电子邮件',
    },
    'u7ecerex': {
      'tr': 'Password',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'el': 'Σύνθημα',
      'en': 'Password',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'it': 'Password',
      'ja': 'パスワード',
      'ru': 'Пароль',
      'zh_Hans': '密码',
    },
    'ezgjjnvq': {
      'tr': 'Confirm Password',
      'ar': 'تأكيد كلمة المرور',
      'de': 'Passwort bestätigen',
      'el': 'Επιβεβαίωση κωδικού πρόσβασης',
      'en': 'Confirm Password',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'hi': 'पासवर्ड की पुष्टि कीजिये',
      'it': 'Conferma password',
      'ja': 'パスワードを認証する',
      'ru': 'Подтвердите пароль',
      'zh_Hans': '确认密码',
    },
    '7halexj9': {
      'tr': 'Hesap Oluştur ',
      'ar': 'إنشاء حساب',
      'de': 'Benutzerkonto erstellen',
      'el': 'Δημιουργία λογαριασμού',
      'en': 'Create Account',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'ru': 'Зарегистрироваться',
      'zh_Hans': '创建账户',
    },
    'cargqphb': {
      'tr': 'Zaten bir hesabınız var mı?',
      'ar': 'هل لديك حساب بالفعل؟',
      'de': 'Haben Sie bereits ein Konto?',
      'el': 'Έχετε ήδη λογαριασμό;',
      'en': 'Do you already have an account?',
      'es': '¿Ya tienes una cuenta?',
      'fr': 'Avez-vous déjà un compte?',
      'hi': 'क्या पहले से आपका खाता है?',
      'it': 'Hai già un account?',
      'ja': 'すでにアカウントをお持ちですか?',
      'ru': 'У вас уже есть аккаунт?',
      'zh_Hans': '您已有帐户吗？',
    },
    'sianevz0': {
      'tr': '  Buradan giriş yap',
      'ar': 'تسجيل الدخول هنا',
      'de': 'Hier anmelden',
      'el': 'Συνδεθείτε εδώ',
      'en': 'Log in here',
      'es': 'Inicie sesión aquí',
      'fr': 'Connectez-vous ici',
      'hi': 'यहां लॉगिन करें',
      'it': 'Accedi qui',
      'ja': 'ここからログイン',
      'ru': 'Войти здесь',
      'zh_Hans': '在此登录',
    },
    't2ags2ie': {
      'tr': 'UserName',
      'ar': 'اسم المستخدم',
      'de': 'Benutzername',
      'el': 'Ονομα χρήστη',
      'en': 'User Name',
      'es': 'Nombre de usuario',
      'fr': 'Nom d\'utilisateur',
      'hi': 'उपयोगकर्ता नाम',
      'it': 'Nome utente',
      'ja': 'ユーザー名',
      'ru': 'Имя пользователя',
      'zh_Hans': '用户名',
    },
    'xhgdoo3a': {
      'tr': 'Overall',
      'ar': 'إجمالي',
      'de': 'Gesamt',
      'el': 'Ολικός',
      'en': 'Overall',
      'es': 'En general',
      'fr': 'Dans l\'ensemble',
      'hi': 'कुल मिलाकर',
      'it': 'Complessivamente',
      'ja': '全体',
      'ru': 'Общий',
      'zh_Hans': '全面的',
    },
    'eshh9ypk': {
      'tr': '5',
      'ar': '5',
      'de': '5',
      'el': '5',
      'en': '5',
      'es': '5',
      'fr': '5',
      'hi': '5',
      'it': '5',
      'ja': '5',
      'ru': '5',
      'zh_Hans': '5',
    },
    'kqb69gys': {
      'tr':
          'Nice outdoor courts, solid concrete and good hoops for the neighborhood.',
      'ar': 'ملاعب خارجية جميلة، وخرسانة صلبة وأطواق جيدة للجيران.',
      'de':
          'Schöne Außenplätze, solider Beton und gute Körbe für die Nachbarschaft.',
      'el':
          'Ωραία εξωτερικά γήπεδα, συμπαγές σκυρόδεμα και καλά στεφάνια για τη γειτονιά.',
      'en':
          'Nice outdoor courts, solid concrete and good hoops for the neighborhood.',
      'es':
          'Bonitas canchas al aire libre, concreto solido y buenos aros para el barrio.',
      'fr':
          'De beaux terrains extérieurs, du béton solide et de bons paniers pour le quartier.',
      'hi': 'अच्छे आउटडोर कोर्ट, ठोस कंक्रीट और पड़ोस के लिए अच्छे हुप्स।',
      'it':
          'Bei campi all\'aperto, cemento solido e buoni canestri per il quartiere.',
      'ja': '素晴らしい屋外コート、頑丈なコンクリート、近所に最適なバスケットボールコート。',
      'ru':
          'Хорошие открытые корты, прочный бетон и хорошие баскетбольные корзины для всего района.',
      'zh_Hans': '漂亮的室外球场、坚固的混凝土和适合社区的优质篮球架。',
    },
    'ck4p62bq': {
      'tr': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'el': 'Σπίτι',
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'it': 'Casa',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // Profile05
  {
    'f2cn37w7': {
      'tr': 'AD SOYAD',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'NAME SURNAME',
      'es': 'NOMBRE APELLIDO',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '名前 姓',
      'ru': 'ИМЯ ФАМИЛИЯ',
      'zh_Hans': '名字 姓氏',
    },
    'dd88gjxz': {
      'tr': 'andrea@domainname.com',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'andrea@domainname.com',
      'es': 'andrea@nombrededominio.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'andrea@domainname.com',
      'ru': 'andrea@domainname.com',
      'zh_Hans': 'andrea@domainname.com',
    },
    'ozzhdynx': {
      'tr': 'Çıkış Yap',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Log Out',
      'es': 'Finalizar la sesión',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ログアウト',
      'ru': 'Выйти',
      'zh_Hans': '登出',
    },
    's64bv1jf': {
      'tr': 'Edit Profile',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Edit Profile',
      'es': 'Editar perfil',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プロフィールを編集',
      'ru': 'Редактировать профиль',
      'zh_Hans': '编辑个人资料',
    },
    'm0zdh9pf': {
      'tr': 'Hesap Ayarları',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Account Settings',
      'es': 'Configuraciones de la cuenta',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'アカウント設定',
      'ru': 'Настройки учетной записи',
      'zh_Hans': '帐户设置',
    },
    '5g7k8hro': {
      'tr': 'Geçmiş Aramalar',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Past Searches',
      'es': 'Búsquedas pasadas',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '過去の検索',
      'ru': 'Прошлые поиски',
      'zh_Hans': '过去的搜索',
    },
    'fh688uth': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'sk7fjfd1': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'mkguti6p': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'j41a86lb': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'ezxrsu3q': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'lsf0dpvu': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'hb7wmcx7': {
      'tr': '__',
      'ar': '',
      'de': '',
      'el': '',
      'en': '__',
      'es': '__',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '__',
      'ru': '__',
      'zh_Hans': '__',
    },
  },
  // List06UserSearch
  {
    '1db238yk': {
      'tr': 'Hello World',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Hello World',
      'es': 'Hola Mundo',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'こんにちは世界',
      'ru': 'Привет, мир',
      'zh_Hans': '你好世界',
    },
    '0sfkhq1k': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // List06UserSearchCopy
  {
    'hsfwgdkw': {
      'tr': 'Add Members',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Add Members',
      'es': 'Agregar miembros',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'メンバーを追加',
      'ru': 'Добавить участников',
      'zh_Hans': '添加成员',
    },
    '0em7okge': {
      'tr': 'Search members...',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Search members...',
      'es': 'Buscar miembros...',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'メンバーを検索...',
      'ru': 'Поиск участников...',
      'zh_Hans': '搜索成员...',
    },
    'z8sgal50': {
      'tr': 'Members in Project',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Members in Project',
      'es': 'Miembros en el Proyecto',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プロジェクトメンバー',
      'ru': 'Участники проекта',
      'zh_Hans': '项目成员',
    },
    'yxjk3igv': {
      'tr': 'UserName',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'User Name',
      'es': 'Nombre de usuario',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー名',
      'ru': 'Имя пользователя',
      'zh_Hans': '用户名',
    },
    '99bqtai4': {
      'tr': 'Remove',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Remove',
      'es': 'Eliminar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '取り除く',
      'ru': 'Удалять',
      'zh_Hans': '消除',
    },
    'fhp3vub1': {
      'tr': 'UserName',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'User Name',
      'es': 'Nombre de usuario',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー名',
      'ru': 'Имя пользователя',
      'zh_Hans': '用户名',
    },
    '585j6xwz': {
      'tr': 'Remove',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Remove',
      'es': 'Eliminar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '取り除く',
      'ru': 'Удалять',
      'zh_Hans': '消除',
    },
    '51zvs6ls': {
      'tr': 'UserName',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'User Name',
      'es': 'Nombre de usuario',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー名',
      'ru': 'Имя пользователя',
      'zh_Hans': '用户名',
    },
    'h1lohcyg': {
      'tr': 'Remove',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Remove',
      'es': 'Eliminar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '取り除く',
      'ru': 'Удалять',
      'zh_Hans': '消除',
    },
    'q5p2uni0': {
      'tr': 'Add Members',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Add Members',
      'es': 'Agregar miembros',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'メンバーを追加',
      'ru': 'Добавить участников',
      'zh_Hans': '添加成员',
    },
    'pxl2q8ta': {
      'tr': 'user@domainname.com',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'user@domainname.com',
      'es': 'usuario@nombrededominio.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー@ドメイン名.com',
      'ru': 'пользователь@имя_домена.com',
      'zh_Hans': '用户@域名.com',
    },
    '0mmszwov': {
      'tr': 'View',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'View',
      'es': 'Vista',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ビュー',
      'ru': 'Вид',
      'zh_Hans': '看法',
    },
    '7jgcyogz': {
      'tr': 'user@domainname.com',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'user@domainname.com',
      'es': 'usuario@nombrededominio.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー@ドメイン名.com',
      'ru': 'пользователь@имя_домена.com',
      'zh_Hans': '用户@域名.com',
    },
    'w0nqar4c': {
      'tr': 'View',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'View',
      'es': 'Vista',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ビュー',
      'ru': 'Вид',
      'zh_Hans': '看法',
    },
    'b2qqz5zh': {
      'tr': 'Username',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Username',
      'es': 'Nombre de usuario',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー名',
      'ru': 'Имя пользователя',
      'zh_Hans': '用户名',
    },
    'm6vjlpmn': {
      'tr': 'user@domainname.com',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'user@domainname.com',
      'es': 'usuario@nombrededominio.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー@ドメイン名.com',
      'ru': 'пользователь@имя_домена.com',
      'zh_Hans': '用户@域名.com',
    },
    'qovkz9bm': {
      'tr': 'View',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'View',
      'es': 'Vista',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ビュー',
      'ru': 'Вид',
      'zh_Hans': '看法',
    },
    'mjtpwhwi': {
      'tr': 'Username',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Username',
      'es': 'Nombre de usuario',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー名',
      'ru': 'Имя пользователя',
      'zh_Hans': '用户名',
    },
    'smz62e64': {
      'tr': 'user@domainname.com',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'user@domainname.com',
      'es': 'usuario@nombrededominio.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー@ドメイン名.com',
      'ru': 'пользователь@имя_домена.com',
      'zh_Hans': '用户@域名.com',
    },
    '3hmr48eg': {
      'tr': 'View',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'View',
      'es': 'Vista',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ビュー',
      'ru': 'Вид',
      'zh_Hans': '看法',
    },
    'qxe5w53y': {
      'tr': 'user@domainname.com',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'user@domainname.com',
      'es': 'usuario@nombrededominio.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ユーザー@ドメイン名.com',
      'ru': 'пользователь@имя_домена.com',
      'zh_Hans': '用户@域名.com',
    },
    '5j0shosk': {
      'tr': 'View',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'View',
      'es': 'Vista',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ビュー',
      'ru': 'Вид',
      'zh_Hans': '看法',
    },
    'amteo7gt': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // List06UserSearchCopy2
  {
    'iq2fadqg': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // anasayfa
  {
    '78da7h3a': {
      'tr': '   FRUVIA\'YA\nHOŞGELDİNİZ',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'WELCOME TO FRUVIA',
      'es': 'BIENVENIDO A FRUVIA',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'フルビアへようこそ',
      'ru': 'ДОБРО ПОЖАЛОВАТЬ В ФРУВИЮ',
      'zh_Hans': '欢迎来到 FRUVIA',
    },
    'a427o43v': {
      'tr': 'Bir meyve fotoğrafı yükle, gerisini bize bırak.',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Upload a fruit photo and leave the rest to us.',
      'es': 'Sube una foto de la fruta y déjanos el resto a nosotros.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '果物の写真をアップロードして、あとは私たちにお任せください。',
      'ru': 'Загрузите фотографию фрукта и предоставьте все остальное нам.',
      'zh_Hans': '上传一张水果照片，剩下的就交给我们吧。',
    },
    'ivpro8y1': {
      'tr': 'Galerinizden bir fotoğraf seçin',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Select a photo from your gallery',
      'es': 'Selecciona una foto de tu galería',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ギャラリーから写真を選択してください',
      'ru': 'Выберите фотографию из вашей галереи',
      'zh_Hans': '从您的图库中选择一张照片',
    },
    'l7nlvy04': {
      'tr': 'RESİM SEÇ',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'SELECT PICTURE',
      'es': 'SELECCIONAR IMAGEN',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '画像を選択',
      'ru': 'ВЫБЕРИТЕ КАРТИНКУ',
      'zh_Hans': '选择图片',
    },
    '2ar4qp4j': {
      'tr': 'Sonuç',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Conclusion',
      'es': 'Conclusión',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '結論',
      'ru': 'Заключение',
      'zh_Hans': '结论',
    },
    'qudvd7jq': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // anasayfaCopy
  {
    'id6oes40': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // anasayfaCopyCopy
  {
    'qkupvyw5': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // drawerdeneme
  {
    '5xe7tunj': {
      'tr': 'Hello World',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Hello World',
      'es': 'Hola Mundo',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'こんにちは世界',
      'ru': 'Привет, мир',
      'zh_Hans': '你好世界',
    },
    'sb0ypys0': {
      'tr': 'Password',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Password',
      'es': 'Contraseña',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'パスワード',
      'ru': 'Пароль',
      'zh_Hans': '密码',
    },
    '5rjervoc': {
      'tr': 'Button',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Button',
      'es': 'Botón',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ボタン',
      'ru': 'Кнопка',
      'zh_Hans': '按钮',
    },
    'eybm3xwo': {
      'tr': 'Button',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Button',
      'es': 'Botón',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ボタン',
      'ru': 'Кнопка',
      'zh_Hans': '按钮',
    },
    'x2gxk9qi': {
      'tr': 'Button',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Button',
      'es': 'Botón',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ボタン',
      'ru': 'Кнопка',
      'zh_Hans': '按钮',
    },
    'tzwe0om7': {
      'tr': 'Hello World',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Hello World',
      'es': 'Hola Mundo',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'こんにちは世界',
      'ru': 'Привет, мир',
      'zh_Hans': '你好世界',
    },
    'x3r3epze': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    '0m9s8k54': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    '7ffp153c': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    '921h0kb1': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    '1fe2wpr5': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'dpp5j2yb': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    '94cyst68': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'gdde5qot': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'h9ai93ir': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'm42rmdbt': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // List08ProductList
  {
    'treilbou': {
      'tr': 'Order Now',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Order Now',
      'es': 'Ordene ahora',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '今すぐ注文',
      'ru': 'Заказать сейчас',
      'zh_Hans': '立即订购',
    },
    'hhh34whd': {
      'tr': 'Our menu is below',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Our menu is below',
      'es': 'Nuestro menú se encuentra a continuación',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'メニューは以下の通りです',
      'ru': 'Наше меню ниже',
      'zh_Hans': '我们的菜单如下',
    },
    'r4su1nry': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'y7qlb6js': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    '8gwf49vl': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    '3uuui11y': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'te66ujrf': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'sz9zcuzc': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'v706xffa': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    '9al41qyy': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'ejlt4bz3': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'pkuppy7g': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'r0rpp03i': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'jvs6ww0f': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'tgamdde4': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'f84xdxin': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'kdwyulv9': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    '33gevqzk': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    '9q6bja6w': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    '3s9t80g2': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'h2r5pmm7': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // MenuSayfasi
  {
    '18aj1hqf': {
      'tr': 'AD SOYAD',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'NAME SURNAME',
      'es': 'NOMBRE APELLIDO',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '名前 姓',
      'ru': 'ИМЯ ФАМИЛИЯ',
      'zh_Hans': '名字 姓氏',
    },
    '9ov767h4': {
      'tr': 'andrea@domainname.com',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'andrea@domainname.com',
      'es': 'andrea@nombrededominio.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'andrea@domainname.com',
      'ru': 'andrea@domainname.com',
      'zh_Hans': 'andrea@domainname.com',
    },
    'rj6ckw0h': {
      'tr': 'SINIRSIZ OL',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'BE UNLIMITED',
      'es': 'SER ILIMITADO',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '無限の可能性',
      'ru': 'БУДЬТЕ БЕЗГРАНИЧНЫ',
      'zh_Hans': '无限',
    },
    '1ogolbi8': {
      'tr': 'Çıkış Yap',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Log Out',
      'es': 'Finalizar la sesión',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ログアウト',
      'ru': 'Выйти',
      'zh_Hans': '登出',
    },
    'sjnh6oa5': {
      'tr': 'Edit Profile',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Edit Profile',
      'es': 'Editar perfil',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プロフィールを編集',
      'ru': 'Редактировать профиль',
      'zh_Hans': '编辑个人资料',
    },
    'zyjrxa1m': {
      'tr': 'Hesap Ayarları',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Account Settings',
      'es': 'Configuraciones de la cuenta',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'アカウント設定',
      'ru': 'Настройки учетной записи',
      'zh_Hans': '帐户设置',
    },
    'l69b8vk9': {
      'tr': 'Geçmiş Aramalar',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Past Searches',
      'es': 'Búsquedas pasadas',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '過去の検索',
      'ru': 'Прошлые поиски',
      'zh_Hans': '过去的搜索',
    },
    'hr6yls6m': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    '0r8tbo99': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'ielx5yy2': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    '1o8ngg2i': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'lepk6pzc': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'ltvy5axo': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    '4mftpatv': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    '81vtn6up': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'vcyycch2': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    '5mhbtnxv': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'a5ytkh8u': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    '92r8zjzq': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'mrurd20l': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    's740nb3y': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'prwndqqo': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'op0b6fnn': {
      'tr': 'Title',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Title',
      'es': 'Título',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'タイトル',
      'ru': 'Заголовок',
      'zh_Hans': '标题',
    },
    'xtmxawoq': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    '971z3n85': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'wr9c2gmv': {
      'tr': '__',
      'ar': '',
      'de': '',
      'el': '',
      'en': '__',
      'es': '__',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '__',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Gecmis
  {
    'thu19kuj': {
      'tr': 'Görsel Analiz Geçmişi',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Visual Analytics History',
      'es': 'Historial de análisis visual',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ビジュアルアナリティクスの歴史',
      'ru': 'История визуальной аналитики',
      'zh_Hans': '可视化分析历史',
    },
    'snlw3i9k': {
      'tr': 'Besin bilgisi :',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Nutritional information:',
      'es': 'Información nutricional:',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '栄養成分表示:',
      'ru': 'Пищевая ценность:',
      'zh_Hans': '营养信息：',
    },
    '4ak9t2d4': {
      'tr': '__',
      'ar': '',
      'de': '',
      'el': '',
      'en': '__fg',
      'es': '__fg',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '__fg',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Abonelik
  {
    'cwha6laj': {
      'tr': 'Haftalık Abonelik',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Weekly Subscription',
      'es': 'Suscripción semanal',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '週刊サブスクリプション',
      'ru': 'Еженедельная подписка',
      'zh_Hans': '每周订阅',
    },
    '81jtopp9': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    '96h00p8w': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'nc9nlxd0': {
      'tr': 'Aylık Abonelik',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Monthly Subscription',
      'es': 'Suscripción mensual',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '月額サブスクリプション',
      'ru': 'Ежемесячная подписка',
      'zh_Hans': '每月订阅',
    },
    'teht4v4j': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'fd297whp': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'q368u0el': {
      'tr': '5 Kerelik Paket',
      'ar': '',
      'de': '',
      'el': '',
      'en': '5-Time Package',
      'es': 'Paquete de 5 veces',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '5回パッケージ',
      'ru': '5-кратный пакет',
      'zh_Hans': '5次套餐',
    },
    '7enev493': {
      'tr': 'Subtext',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subtext',
      'es': 'Sentido solapado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブテキスト',
      'ru': 'Подтекст',
      'zh_Hans': '潜台词',
    },
    'msufnyip': {
      'tr': '\$11.00',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$11.00',
      'es': '\$11.00',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '11.00ドル',
      'ru': '11,00 долларов США',
      'zh_Hans': '11.00 美元',
    },
    'genmn2me': {
      'tr': '__fg',
      'ar': '',
      'de': '',
      'el': '',
      'en': '__fg',
      'es': '__fg',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '__fg',
      'ru': '__fg',
      'zh_Hans': '__fg',
    },
  },
  // chatkismi
  {
    'zqsl4jvh': {
      'tr': 'RUVİA',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'RUVIA',
      'es': 'RUVIA',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ルビア',
      'ru': 'РУВИЯ',
      'zh_Hans': '鲁维亚',
    },
    'zget6qt3': {
      'tr': 'Galerinizden bir fotoğraf seçin',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Select a photo from your gallery',
      'es': 'Selecciona una foto de tu galería',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ギャラリーから写真を選択してください',
      'ru': 'Выберите фотографию из вашей галереи',
      'zh_Hans': '从您的图库中选择一张照片',
    },
    'zdsmmbcg': {
      'tr': 'RESİM SEÇ',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'SELECT PICTURE',
      'es': 'SELECCIONAR IMAGEN',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '画像を選択',
      'ru': 'ВЫБЕРИТЕ КАРТИНКУ',
      'zh_Hans': '选择图片',
    },
    'dfnatetg': {
      'tr': 'İşlem Tamamlandı',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Transaction Completed',
      'es': 'Transacción completada',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '取引完了',
      'ru': 'Транзакция завершена',
      'zh_Hans': '交易完成',
    },
    '9ah56iqd': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // AbonelikCopy
  {
    'cs96sf4a': {
      'tr': 'Abonelik Planı',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subscription Plan',
      'es': 'Plan de suscripción',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブスクリプションプラン',
      'ru': 'План подписки',
      'zh_Hans': '订阅计划',
    },
    'vygf6kjm': {
      'tr': 'Klasik Plan',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Classic Plan',
      'es': 'Plan Clásico',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'クラシックプラン',
      'ru': 'Классический план',
      'zh_Hans': '经典计划',
    },
    'zjkydzib': {
      'tr': 'Popüler',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Popular',
      'es': 'Popular',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '人気のある',
      'ru': 'Популярный',
      'zh_Hans': '受欢迎的',
    },
    'fmq3eyql': {
      'tr': '20 TL',
      'ar': '',
      'de': '',
      'el': '',
      'en': '20 TL',
      'es': '20 TL',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '20トルコリラ',
      'ru': '20 лир',
      'zh_Hans': '20 土耳其里拉',
    },
    'goh35w0x': {
      'tr': 'Haftalık',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Weekly',
      'es': 'Semanalmente',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '週刊',
      'ru': 'Еженедельно',
      'zh_Hans': '每周',
    },
    'c500y7zf': {
      'tr': 'Sınırsız erişim',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Unlimited access',
      'es': 'Acceso ilimitado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '無制限アクセス',
      'ru': 'Неограниченный доступ',
      'zh_Hans': '无限制访问',
    },
    'txn55yf3': {
      'tr': 'Reklamsız gösterim',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Ad-free display',
      'es': 'Pantalla sin publicidad',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '広告なしのディスプレイ',
      'ru': 'Отображение без рекламы',
      'zh_Hans': '无广告显示',
    },
    'd5hlawzs': {
      'tr': 'Hızlı cevap',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Quick answer',
      'es': 'Respuesta rápida',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '簡単な答え',
      'ru': 'Быстрый ответ',
      'zh_Hans': '快速回答',
    },
    'ig3kf3q3': {
      'tr': 'SEÇ',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'SELECT',
      'es': 'SELECCIONAR',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '選択',
      'ru': 'ВЫБИРАТЬ',
      'zh_Hans': '选择',
    },
    't2hyy1h9': {
      'tr': '__',
      'ar': '',
      'de': '',
      'el': '',
      'en': '__fg',
      'es': '__fg',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '__fg',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // anasayfaCopy2
  {
    '09wx1qfu': {
      'tr': 'RUVİA',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'RUVIA',
      'es': 'RUVIA',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ルビア',
      'ru': 'РУВИЯ',
      'zh_Hans': '鲁维亚',
    },
    'd0u0h2i6': {
      'tr': '   FRUVIA\'YA\nHOŞGELDİNİZ',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'WELCOME TO FRUVIA',
      'es': 'BIENVENIDO A FRUVIA',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'フルビアへようこそ',
      'ru': 'ДОБРО ПОЖАЛОВАТЬ В ФРУВИЮ',
      'zh_Hans': '欢迎来到 FRUVIA',
    },
    'uee13k5o': {
      'tr': 'Start chatting with ChattyAI now.',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Start chatting with ChattyAI now.',
      'es': 'Empiece a chatear con ChattyAI ahora.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '今すぐChattyAIとチャットを始めましょう。',
      'ru': 'Начните общаться с ChattyAI прямо сейчас.',
      'zh_Hans': '立即开始与 ChattyAI 聊天。',
    },
    'i56cw4hc': {
      'tr': 'You can ask me anything.',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'You can ask me anything.',
      'es': 'Puedes preguntarme cualquier cosa.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '何でも聞いてください。',
      'ru': 'Вы можете спросить меня о чем угодно.',
      'zh_Hans': '你可以问我任何事情。',
    },
    'd63fnr1x': {
      'tr': 'Galerinizden bir fotoğraf seçin',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Select a photo from your gallery',
      'es': 'Selecciona una foto de tu galería',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ギャラリーから写真を選択してください',
      'ru': 'Выберите фотографию из вашей галереи',
      'zh_Hans': '从您的图库中选择一张照片',
    },
    'bg0a2wrs': {
      'tr': 'RESİM SEÇ',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'SELECT PICTURE',
      'es': 'SELECCIONAR IMAGEN',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '画像を選択',
      'ru': 'ВЫБЕРИТЕ КАРТИНКУ',
      'zh_Hans': '选择图片',
    },
    'ok0nbkdu': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home',
      'es': 'Hogar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '家',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // dil
  {
    'vygcvr2h': {
      'tr': 'Premiuma Geç',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Go Premium',
      'es': 'Hazte Premium',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プレミアムへ',
      'ru': 'Перейти на Премиум',
      'zh_Hans': '升级至高级版',
    },
    '0yeq5cmn': {
      'tr': '__fg',
      'ar': '',
      'de': '',
      'el': '',
      'en': '__fg',
      'es': '__fg',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '__fg',
      'ru': '__fg',
      'zh_Hans': '__fg',
    },
  },
  // HomePageCopy
  {
    '8mylpfll': {
      'tr': 'Hello World',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Hello World',
      'es': 'Hola Mundo',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'こんにちは世界',
      'ru': 'Привет, мир',
      'zh_Hans': '你好世界',
    },
    'uw15ym3r': {
      'tr': 'Hello World',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Hello World',
      'es': 'Hola Mundo',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'こんにちは世界',
      'ru': 'Привет, мир',
      'zh_Hans': '你好世界',
    },
    'q8iftr98': {
      'tr': 'Hello World',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Hello World',
      'es': 'Hola Mundo',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'こんにちは世界',
      'ru': 'Привет, мир',
      'zh_Hans': '你好世界',
    },
    '38bdim9v': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // HomePageCopy2
  {
    'ebwh84rn': {
      'tr': 'Home',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // HesapAyarlariCopy
  {
    'flr57f66': {
      'tr': 'Fruvia',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Fruvia',
      'es': 'Fruvia',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'フルビア',
      'ru': 'Фрувия',
      'zh_Hans': '弗鲁维亚',
    },
    'f5lfzjkg': {
      'tr': '[Email]',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'andrea@domainname.com',
      'es': 'andrea@nombrededominio.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'andrea@domainname.com',
      'ru': 'andrea@domainname.com',
      'zh_Hans': 'andrea@domainname.com',
    },
    'efmdmu7e': {
      'tr': 'Premiuma Geç',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Go Premium',
      'es': 'Hazte Premium',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プレミアムへ',
      'ru': 'Перейти на Премиум',
      'zh_Hans': '升级至高级版',
    },
    '699l1df2': {
      'tr': 'Çıkış Yap',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Log Out',
      'es': 'Finalizar la sesión',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ログアウト',
      'ru': 'Выйти',
      'zh_Hans': '登出',
    },
    'oex7cl4f': {
      'tr': 'Fruvia\'yı Paylaş',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Share Fruvia',
      'es': 'Compartir Fruvia',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'フルビアをシェアする',
      'ru': 'Поделиться Фрувией',
      'zh_Hans': '分享 Fruvia',
    },
    'b7i88vj8': {
      'tr': 'Bizi Değerlendir',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Rate Us',
      'es': 'Calificanos',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '評価してください',
      'ru': 'Оцените нас',
      'zh_Hans': '评价我们',
    },
    '0x38a0za': {
      'tr': 'Dil',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Language',
      'es': 'Idioma',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '言語',
      'ru': 'Язык',
      'zh_Hans': '语言',
    },
    'i1yoripd': {
      'tr': 'Bizden Daha Fazla Uygulama',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'More Apps From Us',
      'es': 'Más aplicaciones nuestras',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'その他のアプリ',
      'ru': 'Больше приложений от нас',
      'zh_Hans': '我们的更多应用',
    },
    '6rx4s62y': {
      'tr': 'SSS ve Destek',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'FAQ and Support',
      'es': 'Preguntas frecuentes y soporte',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'FAQとサポート',
      'ru': 'Часто задаваемые вопросы и поддержка',
      'zh_Hans': '常见问题和支持',
    },
    'gs88ka2f': {
      'tr': 'Promasyon kodu',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Promotion code',
      'es': 'Código de promoción',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プロモーションコード',
      'ru': 'Промокод',
      'zh_Hans': '促销代码',
    },
    'esrps009': {
      'tr': 'Kullanım Koşulları',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Terms of Use',
      'es': 'Condiciones de uso',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '利用規約',
      'ru': 'Условия эксплуатации',
      'zh_Hans': '使用条款',
    },
    '5pz2nwza': {
      'tr': 'Gizlilik Politikası',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Privacy Policy',
      'es': 'política de privacidad',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プライバシーポリシー',
      'ru': 'политика конфиденциальности',
      'zh_Hans': '隐私政策',
    },
    'bzhd6nm4': {
      'tr': 'Premiuma Geç',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Go Premium',
      'es': 'Hazte Premium',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プレミアムへ',
      'ru': 'Перейти на Премиум',
      'zh_Hans': '升级至高级版',
    },
    '12ymzb8f': {
      'tr': '__',
      'ar': '',
      'de': '',
      'el': '',
      'en': '__fg',
      'es': '__fg',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '__fg',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // HistoryPage
  {
    'm1iq71lf': {
      'tr': 'Görsel Analiz Geçmişi',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Visual Analytics History',
      'es': 'Historial de análisis visual',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ビジュアルアナリティクスの歴史',
      'ru': 'История визуальной аналитики',
      'zh_Hans': '可视化分析历史',
    },
    'bvjnkxgk': {
      'tr': 'Yemek Analizi',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Food Analysis',
      'es': 'Análisis de alimentos',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '食品分析',
      'ru': 'Анализ продуктов питания',
      'zh_Hans': '食品分析',
    },
    '8ecqo723': {
      'tr': '11 Aralık 2024',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'December 11, 2024',
      'es': '11 de diciembre de 2024',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '2024年12月11日',
      'ru': '11 декабря 2024 г.',
      'zh_Hans': '2024年12月11日',
    },
    'yxocd07d': {
      'tr': 'Tamamlandı',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Completed',
      'es': 'Terminado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '完了',
      'ru': 'Завершенный',
      'zh_Hans': '完全的',
    },
  },
  // forgetPassword
  {
    'n7ufkfih': {
      'tr': 'Şifremi Unuttum',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'I forgot my password',
      'es': 'Olvidé mi contraseña',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'パスワードを忘れました',
      'ru': 'Я забыл свой пароль',
      'zh_Hans': '我忘记了密码',
    },
    '8j9zrydx': {
      'tr':
          'E-posta adresinizi girin, size şifre sıfırlama bağlantısı gönderelim.',
      'ar': '',
      'de': '',
      'el': '',
      'en':
          'Enter your email address and we\'ll send you a password reset link.',
      'es':
          'Ingrese su dirección de correo electrónico y le enviaremos un enlace para restablecer su contraseña.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'メールアドレスを入力すると、パスワードリセットリンクが送信されます。',
      'ru':
          'Введите свой адрес электронной почты, и мы вышлем вам ссылку для сброса пароля.',
      'zh_Hans': '输入您的电子邮件地址，我们将向您发送密码重置链接。',
    },
    '6ql9e6j1': {
      'tr': 'Email',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'E-mail',
      'es': 'Correo electrónico',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'Eメール',
      'ru': 'Электронная почта',
      'zh_Hans': '电子邮件',
    },
    'ep51fbee': {
      'tr': 'Sıfırlama Bağlantısı Gönder',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Send Reset Link',
      'es': 'Enviar enlace de restablecimiento',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'リセットリンクを送信',
      'ru': 'Отправить ссылку для сброса',
      'zh_Hans': '发送重置链接',
    },
    'mygwsnem': {
      'tr': 'Şifrenizi hatırladınız mı?',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Did you remember your password?',
      'es': '¿Recordaste tu contraseña?',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'パスワードを覚えていますか?',
      'ru': 'Вы вспомнили свой пароль?',
      'zh_Hans': '您记得密码吗？',
    },
    '125u8np3': {
      'tr': 'Giriş Yap',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Login',
      'es': 'Acceso',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ログイン',
      'ru': 'Авторизоваться',
      'zh_Hans': '登录',
    },
    'bda96ii0': {
      'tr': 'Hesabınıza erişim konusunda sorun mu yaşıyorsunuz?',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Having trouble accessing your account?',
      'es': '¿Tiene problemas para acceder a su cuenta?',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'アカウントにアクセスできない場合',
      'ru': 'Возникли проблемы с доступом к вашей учетной записи?',
      'zh_Hans': '无法访问您的帐户？',
    },
    '76s0v34r': {
      'tr': 'Destek ile İletişime Geçin',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Contact Support',
      'es': 'Contactar con soporte técnico',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サポートに問い合わせる',
      'ru': 'Связаться со службой поддержки',
      'zh_Hans': '联系支持',
    },
  },
  // appbar
  {
    '397ew6dz': {
      'tr': 'RUVİA',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'RUVIA',
      'es': 'RUVIA',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ルビア',
      'ru': 'РУВИЯ',
      'zh_Hans': '鲁维亚',
    },
  },
  // SideNav02
  {
    'jly7kfhb': {
      'tr': 'check.io',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'check.io',
      'es': 'check.io',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'チェック.io',
      'ru': 'check.io',
      'zh_Hans': 'check.io',
    },
    '1rvzrry1': {
      'tr': 'Andrew D.',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Andrew D.',
      'es': 'Andrés D.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'アンドリュー D.',
      'ru': 'Эндрю Д.',
      'zh_Hans': '安德鲁·D.',
    },
    'csq2jtbh': {
      'tr': 'admin@gmail.com',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'admin@gmail.com',
      'es': 'admin@gmail.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'admin@gmail.com',
      'ru': 'admin@gmail.com',
      'zh_Hans': 'admin@gmail.com',
    },
    '0uj0maqu': {
      'tr': 'Platform Navigation',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Platform Navigation',
      'es': 'Navegación de la plataforma',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プラットフォームナビゲーション',
      'ru': 'Навигация по платформе',
      'zh_Hans': '平台导航',
    },
    'x3bg62rz': {
      'tr': 'Dashboard',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Dashboard',
      'es': 'Panel',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ダッシュボード',
      'ru': 'Панель инструментов',
      'zh_Hans': '仪表板',
    },
    'wl62ua8n': {
      'tr': 'Chats',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Chats',
      'es': 'Chats',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'チャット',
      'ru': 'Чаты',
      'zh_Hans': '聊天',
    },
    'z3qcjnpm': {
      'tr': 'Projects',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Projects',
      'es': 'Proyectos',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プロジェクト',
      'ru': 'Проекты',
      'zh_Hans': '项目',
    },
    'axgjane5': {
      'tr': 'Settings',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Settings',
      'es': 'Ajustes',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '設定',
      'ru': 'Настройки',
      'zh_Hans': '设置',
    },
    'm4y26kkb': {
      'tr': 'Notifications',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Notifications',
      'es': 'Notificaciones',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '通知',
      'ru': 'Уведомления',
      'zh_Hans': '通知',
    },
    'aj80m10h': {
      'tr': '12',
      'ar': '',
      'de': '',
      'el': '',
      'en': '12',
      'es': '12',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '12',
      'ru': '12',
      'zh_Hans': '12',
    },
    'uanel07h': {
      'tr': 'Billing',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Billing',
      'es': 'Facturación',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '請求する',
      'ru': 'Биллинг',
      'zh_Hans': '计费',
    },
    'xyj4qqg7': {
      'tr': 'Explore',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Explore',
      'es': 'Explorar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '探検する',
      'ru': 'Исследовать',
      'zh_Hans': '探索',
    },
    'zzgppulx': {
      'tr': 'Light Mode',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Light Mode',
      'es': 'Modo claro',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ライトモード',
      'ru': 'Световой режим',
      'zh_Hans': '灯光模式',
    },
    'uruidvzi': {
      'tr': 'Dark Mode',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Dark Mode',
      'es': 'Modo oscuro',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ダークモード',
      'ru': 'Темный режим',
      'zh_Hans': '黑暗模式',
    },
  },
  // AD
  {
    'mtcgc8eh': {
      'tr': '   FRUVIA\'YA\nHOŞGELDİNİZ',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'WELCOME TO FRUVIA',
      'es': 'BIENVENIDO A FRUVIA',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'フルビアへようこそ',
      'ru': 'ДОБРО ПОЖАЛОВАТЬ В ФРУВИЮ',
      'zh_Hans': '欢迎来到 FRUVIA',
    },
    'dqeanvxm': {
      'tr': 'Start chatting with ChattyAI now.',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Start chatting with ChattyAI now.',
      'es': 'Empiece a chatear con ChattyAI ahora.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '今すぐChattyAIとチャットを始めましょう。',
      'ru': 'Начните общаться с ChattyAI прямо сейчас.',
      'zh_Hans': '立即开始与 ChattyAI 聊天。',
    },
    '9dscvw5x': {
      'tr': 'You can ask me anything.',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'You can ask me anything.',
      'es': 'Puedes preguntarme cualquier cosa.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '何でも聞いてください。',
      'ru': 'Вы можете спросить меня о чем угодно.',
      'zh_Hans': '你可以问我任何事情。',
    },
    'ihppu407': {
      'tr': 'Galerinizden bir fotoğraf seçin',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Select a photo from your gallery',
      'es': 'Selecciona una foto de tu galería',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ギャラリーから写真を選択してください',
      'ru': 'Выберите фотографию из вашей галереи',
      'zh_Hans': '从您的图库中选择一张照片',
    },
    'cna6mma9': {
      'tr': 'RESİM SEÇ',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'SELECT PICTURE',
      'es': 'SELECCIONAR IMAGEN',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '画像を選択',
      'ru': 'ВЫБЕРИТЕ КАРТИНКУ',
      'zh_Hans': '选择图片',
    },
  },
  // side
  {
    'nyz2x0xj': {
      'tr': 'check.io',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'check.io',
      'es': 'check.io',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'チェック.io',
      'ru': 'check.io',
      'zh_Hans': 'check.io',
    },
    'zjx4tq6a': {
      'tr': 'Andrew D.',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Andrew D.',
      'es': 'Andrés D.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'アンドリュー D.',
      'ru': 'Эндрю Д.',
      'zh_Hans': '安德鲁·D.',
    },
    'fjn3auju': {
      'tr': 'admin@gmail.com',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'admin@gmail.com',
      'es': 'admin@gmail.com',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'admin@gmail.com',
      'ru': 'admin@gmail.com',
      'zh_Hans': 'admin@gmail.com',
    },
    '762xroim': {
      'tr': 'Platform Navigation',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Platform Navigation',
      'es': 'Navegación de la plataforma',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プラットフォームナビゲーション',
      'ru': 'Навигация по платформе',
      'zh_Hans': '平台导航',
    },
    'ih188sp4': {
      'tr': 'Dashboard',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Dashboard',
      'es': 'Panel',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ダッシュボード',
      'ru': 'Панель инструментов',
      'zh_Hans': '仪表板',
    },
    'hdtqwup3': {
      'tr': 'Chats',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Chats',
      'es': 'Chats',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'チャット',
      'ru': 'Чаты',
      'zh_Hans': '聊天',
    },
    'qwh8bfzu': {
      'tr': 'Projects',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Projects',
      'es': 'Proyectos',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プロジェクト',
      'ru': 'Проекты',
      'zh_Hans': '项目',
    },
    'bngiesq1': {
      'tr': 'Settings',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Settings',
      'es': 'Ajustes',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '設定',
      'ru': 'Настройки',
      'zh_Hans': '设置',
    },
    'tm2qtzdf': {
      'tr': 'Notifications',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Notifications',
      'es': 'Notificaciones',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '通知',
      'ru': 'Уведомления',
      'zh_Hans': '通知',
    },
    'iaeto6g6': {
      'tr': '12',
      'ar': '',
      'de': '',
      'el': '',
      'en': '12',
      'es': '12',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '12',
      'ru': '12',
      'zh_Hans': '12',
    },
    'yxajny21': {
      'tr': 'Billing',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Billing',
      'es': 'Facturación',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '請求する',
      'ru': 'Биллинг',
      'zh_Hans': '计费',
    },
    'kvdg5tzn': {
      'tr': 'Explore',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Explore',
      'es': 'Explorar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '探検する',
      'ru': 'Исследовать',
      'zh_Hans': '探索',
    },
    'fzwn6ctk': {
      'tr': 'Light Mode',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Light Mode',
      'es': 'Modo claro',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ライトモード',
      'ru': 'Световой режим',
      'zh_Hans': '灯光模式',
    },
    'gkj9ny2l': {
      'tr': 'Dark Mode',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Dark Mode',
      'es': 'Modo oscuro',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ダークモード',
      'ru': 'Темный режим',
      'zh_Hans': '黑暗模式',
    },
  },
  // appbaprofil
  {
    'pd7vsp9w': {
      'tr': 'FRUVİA',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // acilisreklam
  {
    'tfuu509r': {
      'tr': 'Premium Planlar',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Premium Plans',
      'es': 'Planes Premium',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プレミアムプラン',
      'ru': 'Премиум-планы',
      'zh_Hans': '高级计划',
    },
    'yq7j3tz7': {
      'tr': 'Premium',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Premium',
      'es': 'De primera calidad',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プレミアム',
      'ru': 'Премиум',
      'zh_Hans': '优质的',
    },
    'z0g09hyo': {
      'tr': 'Tüm özelliklere erişim',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Access to all features',
      'es': 'Acceso a todas las funciones',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'すべての機能へのアクセス',
      'ru': 'Доступ ко всем функциям',
      'zh_Hans': '访问所有功能',
    },
    'quxp0ndh': {
      'tr': '₺29.99/ay',
      'ar': '',
      'de': '',
      'el': '',
      'en': '₺29.99/month',
      'es': '₺29,99/mes',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '月額₺29.99',
      'ru': '29,99 ₺/месяц',
      'zh_Hans': '₺29.99/月',
    },
    '6hmji7jj': {
      'tr': 'Sınırsız kullanım',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Unlimited use',
      'es': 'Uso ilimitado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '無制限の使用',
      'ru': 'Неограниченное использование',
      'zh_Hans': '无限使用',
    },
    'nteeyxrv': {
      'tr': 'Reklamsız deneyim',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Ad-free experience',
      'es': 'Experiencia sin publicidad',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '広告なしの体験',
      'ru': 'Опыт без рекламы',
      'zh_Hans': '无广告体验',
    },
    '91t6jo1u': {
      'tr': 'Öncelikli destek',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Priority support',
      'es': 'Soporte prioritario',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '優先サポート',
      'ru': 'Приоритетная поддержка',
      'zh_Hans': '优先支持',
    },
    'rr8smlju': {
      'tr': 'Başlat',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Start',
      'es': 'Comenzar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '始める',
      'ru': 'Начинать',
      'zh_Hans': '开始',
    },
    'o1jozbv2': {
      'tr': 'Standart',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Standard',
      'es': 'Estándar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '標準',
      'ru': 'Стандарт',
      'zh_Hans': '标准',
    },
    'hbjrmpdy': {
      'tr': 'Temel özellikler',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Key features',
      'es': 'Características principales',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '主な特徴',
      'ru': 'Ключевые особенности',
      'zh_Hans': '主要特点',
    },
    'htam1krc': {
      'tr': '₺9.99/ay',
      'ar': '',
      'de': '',
      'el': '',
      'en': '₺9.99/month',
      'es': '₺9,99/mes',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '月額9.99₺',
      'ru': '9,99 ₺/месяц',
      'zh_Hans': '₺9.99/月',
    },
    'bhg8xmq9': {
      'tr': 'Günlük 10 kullanım',
      'ar': '',
      'de': '',
      'el': '',
      'en': '10 uses per day',
      'es': '10 usos al día',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '1日10回使用',
      'ru': '10 использований в день',
      'zh_Hans': '每天使用 10 次',
    },
    'l8ntp24p': {
      'tr': 'Temel özellikler',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Key features',
      'es': 'Características principales',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '主な特徴',
      'ru': 'Ключевые особенности',
      'zh_Hans': '主要特点',
    },
    'qa6vdw6h': {
      'tr': 'Reklam içerir',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Contains advertising',
      'es': 'Contiene publicidad',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '広告が含まれています',
      'ru': 'Содержит рекламу',
      'zh_Hans': '包含广告',
    },
    'un52s9v8': {
      'tr': 'Seç',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Choose',
      'es': 'Elegir',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '選ぶ',
      'ru': 'Выбирать',
      'zh_Hans': '选择',
    },
    'wnz22hrs': {
      'tr': 'İstediğin zaman iptal edebilirsin',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'You can cancel anytime',
      'es': 'Puedes cancelar en cualquier momento',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'いつでもキャンセルできます',
      'ru': 'Вы можете отменить в любое время.',
      'zh_Hans': '您可以随时取消',
    },
  },
  // abonelikCopyCopy
  {
    'b5gkmu3v': {
      'tr': 'Subscription Plans',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Subscription Plans',
      'es': 'Planes de suscripción',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'サブスクリプションプラン',
      'ru': 'Планы подписки',
      'zh_Hans': '订阅计划',
    },
    '4fg6hgih': {
      'tr': 'Choose the perfect plan for your needs',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Choose the perfect plan for your needs',
      'es': 'Elige el plan perfecto para tus necesidades',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ニーズに最適なプランをお選びください',
      'ru': 'Выберите идеальный план для ваших нужд',
      'zh_Hans': '选择最适合您需求的计划',
    },
    't4ia8cbr': {
      'tr': 'Basic Plan',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Basic Plan',
      'es': 'Plan Básico',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '基本プラン',
      'ru': 'Базовый план',
      'zh_Hans': '基本计划',
    },
    'r92yxhfq': {
      'tr': 'Popular',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Popular',
      'es': 'Popular',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '人気のある',
      'ru': 'Популярный',
      'zh_Hans': '受欢迎的',
    },
    'm6thnel0': {
      'tr': '\$9.99',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$9.99',
      'es': '\$9.99',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '9.99ドル',
      'ru': '9,99 долларов',
      'zh_Hans': '9.99 美元',
    },
    'xqczsvmt': {
      'tr': 'per month',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'per month',
      'es': 'por mes',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '月額',
      'ru': 'помесячно',
      'zh_Hans': '每月',
    },
    'po68llhr': {
      'tr': 'Up to 5 projects',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Up to 5 projects',
      'es': 'Hasta 5 proyectos',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '最大5つのプロジェクト',
      'ru': 'До 5 проектов',
      'zh_Hans': '最多 5 个项目',
    },
    '3zlg9olc': {
      'tr': '10GB storage',
      'ar': '',
      'de': '',
      'el': '',
      'en': '10GB storage',
      'es': '10 GB de almacenamiento',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '10GBのストレージ',
      'ru': '10 ГБ памяти',
      'zh_Hans': '10GB存储空间',
    },
    '91vy4uxb': {
      'tr': 'Email support',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Email support',
      'es': 'Soporte por correo electrónico',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'メールサポート',
      'ru': 'Поддержка по электронной почте',
      'zh_Hans': '电子邮件支持',
    },
    '7poi676z': {
      'tr': 'Get Started',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Get Started',
      'es': 'Empezar',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '始める',
      'ru': 'Начать',
      'zh_Hans': '开始',
    },
    'q2cfm1ug': {
      'tr': 'Pro Plan',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Pro Plan',
      'es': 'Plan Pro',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プロプラン',
      'ru': 'Профессиональный план',
      'zh_Hans': '专业计划',
    },
    'zfuh8k9a': {
      'tr': '\$19.99',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$19.99',
      'es': '\$19.99',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '19.99ドル',
      'ru': '19,99 долларов США',
      'zh_Hans': '19.99 美元',
    },
    '4ff47wcn': {
      'tr': 'per month',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'per month',
      'es': 'por mes',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '月額',
      'ru': 'помесячно',
      'zh_Hans': '每月',
    },
    'yiq2kd5f': {
      'tr': 'Unlimited projects',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Unlimited projects',
      'es': 'Proyectos ilimitados',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '無制限のプロジェクト',
      'ru': 'Неограниченное количество проектов',
      'zh_Hans': '无限项目',
    },
    'if9cgcvn': {
      'tr': '100GB storage',
      'ar': '',
      'de': '',
      'el': '',
      'en': '100GB storage',
      'es': '100 GB de almacenamiento',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '100GBのストレージ',
      'ru': '100 ГБ памяти',
      'zh_Hans': '100GB存储空间',
    },
    '7z6j3yl5': {
      'tr': 'Priority support',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Priority support',
      'es': 'Soporte prioritario',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '優先サポート',
      'ru': 'Приоритетная поддержка',
      'zh_Hans': '优先支持',
    },
    'knt3vb5v': {
      'tr': 'Advanced analytics',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Advanced analytics',
      'es': 'Análisis avanzado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '高度な分析',
      'ru': 'Расширенная аналитика',
      'zh_Hans': '高级分析',
    },
    'mjlox5lq': {
      'tr': 'Upgrade Now',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Upgrade Now',
      'es': 'Actualizar ahora',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '今すぐアップグレード',
      'ru': 'Обновить сейчас',
      'zh_Hans': '立即升级',
    },
    'uqsjl565': {
      'tr': 'Enterprise',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Enterprise',
      'es': 'Empresa',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '企業',
      'ru': 'Предприятие',
      'zh_Hans': '企业',
    },
    'qbqriwpv': {
      'tr': '\$49.99',
      'ar': '',
      'de': '',
      'el': '',
      'en': '\$49.99',
      'es': '\$49.99',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '49.99ドル',
      'ru': '49,99 долларов США',
      'zh_Hans': '49.99美元',
    },
    'li0qb8yx': {
      'tr': 'per month',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'per month',
      'es': 'por mes',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '月額',
      'ru': 'помесячно',
      'zh_Hans': '每月',
    },
    'o7kq344t': {
      'tr': 'Everything in Pro',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Everything in Pro',
      'es': 'Todo en Pro',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'Proのすべて',
      'ru': 'Все в Pro',
      'zh_Hans': 'Pro 中的所有内容',
    },
    'm4ued4o5': {
      'tr': '1TB storage',
      'ar': '',
      'de': '',
      'el': '',
      'en': '1TB storage',
      'es': '1 TB de almacenamiento',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '1TBのストレージ',
      'ru': '1 ТБ хранилища',
      'zh_Hans': '1TB存储空间',
    },
    '0ijyscei': {
      'tr': '24/7 phone support',
      'ar': '',
      'de': '',
      'el': '',
      'en': '24/7 phone support',
      'es': 'Soporte telefónico 24/7',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '24時間365日電話サポート',
      'ru': 'Круглосуточная поддержка по телефону',
      'zh_Hans': '24/7 电话支持',
    },
    '1nqvjgha': {
      'tr': 'Custom integrations',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Custom integrations',
      'es': 'Integraciones personalizadas',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'カスタム統合',
      'ru': 'Пользовательские интеграции',
      'zh_Hans': '自定义集成',
    },
    'vzrnkobm': {
      'tr': 'Contact Sales',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Contact Sales',
      'es': 'Contactar con Ventas',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '営業担当者へのお問い合わせ',
      'ru': 'Связаться с отделом продаж',
      'zh_Hans': '联系销售人员',
    },
  },
  // nav
  {
    'm6uumgt7': {
      'tr': 'Anasayfa',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Home Page',
      'es': 'Página de inicio',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ホームページ',
      'ru': 'Домашняя страница',
      'zh_Hans': '主页',
    },
    'ouzfr6sv': {
      'tr': 'Geçmiş',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Past',
      'es': 'Pasado',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '過去',
      'ru': 'Прошлое',
      'zh_Hans': '过去的',
    },
    '35f3wtof': {
      'tr': 'Profil',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'Profile',
      'es': 'Perfil',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'プロフィール',
      'ru': 'Профиль',
      'zh_Hans': '轮廓',
    },
  },
  // oneboarddilekran
  {
    'itgx469h': {
      'tr': 'Buradan Dili Ayarlayabilirsin',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'You can set the language here',
      'es': 'Puedes configurar el idioma aquí',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ここで言語を設定できます',
      'ru': 'Вы можете установить язык здесь.',
      'zh_Hans': '您可以在这里设置语言',
    },
  },
  // oneboardabonelik
  {
    'jbtpdm72': {
      'tr': 'Buradan Aboneliklere Göz Atabilirsin.',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'You can browse subscriptions here.',
      'es': 'Puede buscar suscripciones aquí.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ここでサブスクリプションを参照できます。',
      'ru': 'Подписки можно просмотреть здесь.',
      'zh_Hans': '您可以在这里浏览订阅内容。',
    },
  },
  // oneboardkamera
  {
    'z4sifhxu': {
      'tr': 'Buradan Kameranı Açıp Resim Çekebilirsin.',
      'ar': '',
      'de': '',
      'el': '',
      'en': 'From here you can open your camera and take a picture.',
      'es': 'Desde aquí puedes abrir tu cámara y tomar una fotografía.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ここからカメラを開いて写真を撮ることができます。',
      'ru': 'Отсюда вы можете открыть камеру и сделать снимок.',
      'zh_Hans': '从这里您可以打开相机并拍照。',
    },
  },
  // oneboardgaleri
  {
    'iqjr5oms': {
      'tr':
          'Buradan Galaerini Açıp Daha Önceden Çektiğin Fotoğrafı Yükleyebilirsin.',
      'ar': '',
      'de': '',
      'el': '',
      'en':
          'From here you can open your gallery and upload the photo you took before.',
      'es':
          'Desde aquí podrás abrir tu galería y subir la foto que tomaste anteriormente.',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': 'ここからギャラリーを開いて、以前に撮影した写真をアップロードできます。',
      'ru':
          'Отсюда вы можете открыть свою галерею и загрузить сделанную ранее фотографию.',
      'zh_Hans': '您可以从这里打开您的图库并上传之前拍摄的照片。',
    },
  },
  // Miscellaneous
  {
    'g7s1uuqq': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'n02kpdyk': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qbsccnu3': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    '8izm7mk2': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'y013cwyi': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'dd9ss874': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'zneld7jk': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'uwo606pa': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'i6n49ax0': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'wmfq848e': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'op2fodej': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'g1ld4nsg': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'tetk0tjk': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    '6womsvkr': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    '2wdsb447': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'vkp0ahl7': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'i1xwuld7': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'pyn1palw': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'dfkvafxo': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'vjb6ultz': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'chotci6u': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    '3sv0ncdr': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    '504fx3a4': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qso7brv1': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'bzu7tkz6': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    'toauxvbd': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
    '5nsyq0z1': {
      'tr': '',
      'ar': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
